#pragma once

class WindowConstants
{
public:
	static float WIDTH;
	static float HEIGHT;

	static float SPRING_HEIGHT;
	static float MAIN_MENU_BAR_HEIGHT;

	static float SPRING_INFORMATION_WINDOW_WIDTH() { return 400.0f; }
	static float SPRING_INFORMATION_WINDOW_HEIGHT() { return HEIGHT - MAIN_MENU_BAR_HEIGHT; }
	static float SPRING_INFORMATION_WINDOW_POSITION_X() { return 0.0f; }
	static float SPRING_INFORMATION_WINDOW_POSITION_Y() { return MAIN_MENU_BAR_HEIGHT; }

	static float TRAJECTORY_GRAPH_WINDOW_WIDTH() { return TRAJECTORY_GRAPH_WINDOW_HEIGHT(); }
	static float TRAJECTORY_GRAPH_WINDOW_HEIGHT() { return HEIGHT - SPRING_HEIGHT; }
	static float TRAJECTORY_GRAPH_WINDOW_POSITION_X() { return WIDTH - TRAJECTORY_GRAPH_WINDOW_WIDTH(); }
	static float TRAJECTORY_GRAPH_WINDOW_POSITION_Y() { return HEIGHT - TRAJECTORY_GRAPH_WINDOW_HEIGHT(); }

	static float FORCES_GRAPH_WINDOW_WIDTH() { return WIDTH - TRAJECTORY_GRAPH_WINDOW_WIDTH() - SPRING_INFORMATION_WINDOW_WIDTH(); }
	static float FORCES_GRAPH_WINDOW_HEIGHT() { return TRAJECTORY_GRAPH_WINDOW_HEIGHT() / 2.0f; }
	static float FORCES_GRAPH_WINDOW_POSITION_X() { return SPRING_INFORMATION_WINDOW_WIDTH(); }
	static float FORCES_GRAPH_WINDOW_POSITION_Y() { return  HEIGHT - TRAJECTORY_GRAPH_WINDOW_HEIGHT() / 2.0f; }

	static float POSITION_VELOCITY_ACCELERATION_GRAPH_WINDOW_WIDTH() { return WIDTH - TRAJECTORY_GRAPH_WINDOW_WIDTH() - SPRING_INFORMATION_WINDOW_WIDTH();; }
	static float POSITION_VELOCITY_ACCELERATION_GRAPH_WINDOW_HEIGHT() { return TRAJECTORY_GRAPH_WINDOW_HEIGHT() / 2.0f; }
	static float POSITION_VELOCITY_ACCELERATION_GRAPH_WINDOW_POSITION_X() { return SPRING_INFORMATION_WINDOW_WIDTH(); }
	static float POSITION_VELOCITY_ACCELERATION_GRAPH_WINDOW_POSITION_Y() { return TRAJECTORY_GRAPH_WINDOW_POSITION_Y(); }
};
